### ISSUE TITLE
Blog posts styling

### ISSUE THREAD

**Issue by ludekcizinsky** [aitu-dk/webpage#7]
I have couple of comments to blog post styling:
1. Might look better if they are block aligned rather than left aligned
2. the divider line is too thick, @mikasenghaas I think on our website it has the right thickness
3. the text is perhaps too wide, maybe I would make it narrower, again @mikasenghaas your website does good job at that

Bottom line: can we make it a bit more like your teaching content pages? @mikasenghaas It is a little detail but I would say it would again improve the user experience.

**Comment by mikasenghaas** [comment]
1. don't think i agree on the text alignment. i usually find it painful to read block aligned text. but i can implement it and have it visible on a preview deploy.
2. i don't think it is the thickness, but the color. will look into it
3. got it

I think I will add slightly smaller font size by default on regular laptop size. that's something that has been annoying me a bit.
